pipeline {
    agent any

    stages {
        stage('Build Docker Images') {
            steps {
                echo '🔨 Building Docker images...'
                bat 'docker build -t order-service ./order-service'
                bat 'docker build -t payment-service ./payment-service'
            }
        }

        stage('Stop Old Containers') {
            steps {
                echo '🧹 Stopping old containers...'
                bat 'docker rm -f order-service || exit 0'
                bat 'docker rm -f payment-service || exit 0'
            }
        }

        stage('Run New Containers') {
            steps {
                echo '🚀 Running containers...'
                bat 'docker run -d -p 8001:80 --name order-service order-service'
                bat 'docker run -d -p 8002:80 --name payment-service payment-service'
            }
        }
    }
}
